language: java
jdk:
 - oraclejdk7
addons:
  firefox: "23.0.1"
install:
  - git clone https://github.com/arquillian/arquillian-extension-qunit.git
  - mvn install -f arquillian-extension-qunit/pom.xml
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
 - mvn test -Parq-qunit-tests
